name: mobile_pj
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  voxauthflutter:
    path: ./packages/multifatorial

  local_auth:
    path: ./packages/local_auth

  flutter_native_splash: ^2.2.19 
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.2.0
  flutter_bloc: ^8.1.0
  flutter_svg: ^2.0.4
  dio: ^5.2.0
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  shared_preferences: ^2.1.2
  equatable: ^2.0.5
  go_router: ^13.0.1
  freezed_annotation: ^2.2.0
  device_info_plus: ^9.0.2
  google_fonts: ^6.1.0
  brasil_fields: ^1.13.1
  auto_size_text: ^3.0.0
  replay_bloc: ^0.2.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
  table_calendar: ^3.0.9
  uuid: ^4.2.1
  intl: ^0.18.0
  collection: ^1.18.0
  flutter_animate: ^4.3.0
  xml: ^6.5.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  clipboard: ^0.1.3
  qr_code_scanner: ^1.0.1

flutter_native_splash:
  color: "#005BA5"
  image: "assets/images/logo_splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher_foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  freezed: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    # Arquivos HTML
    - assets/html/termo_responsabilidade.html
    - assets/images/banpara-logo.png
    # Imagens
    - assets/images/
    # Ãcones
    - assets/icons/
    